### ISSUE TITLE
Unicode chars...?

### ISSUE THREAD

**Issue by rjmoggach** [Swappsco/koalixerp#1] opened 2016-04-06 15:36 UTC
```
SyntaxError: Non-ASCII character '\xc3' in file
..../koalixcrm-swappsco-dev/international/models.py on line 111,
but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by sebastian-code** [comment] 2016-04-06 21:13
Hi @robmoggach Have you checked the Python version? Originally the software was designed for Python2, but we have been migrating it to Python3, This kind of errors are usually related to the Python version, given than Python2 requires encoding declaration, and Python3 don't because it defaults to UTF-8.

Please check that and let me know if that solves your problem

**Comment by rjmoggach** [comment] 2016-04-06 22:44
I added the encoding string to the first line and it worked fine - thanks

**Comment by sebastian-code** [comment] 2016-04-07 01:33
I'm pleased than it worked for you, closing the issue now.

**Closed as completed by sebastian-code** 2016-04-07 01:33 UTC
